/**
 * Shape definition file (easy to edit).
 *
 * Export: SHAPES (array)
 *
 * Each shape object:
 * {
 *   id: string (unique),
 *   name: string,
 *   grid: string[]  // rows of "X" and "." (or spaces) e.g. ["XXX",".X."]
 *   color: string   // hex
 *   difficulty: number,
 *
 *   // Optional behaviour overrides:
 *   rotation: {
 *     mode: "any" | "none" | "custom",
 *     allowed?: number[] // list of rotation states allowed (0..3) if mode="custom"
 *   },
 *
 *   // Optional render/style overrides:
 *   style: {
 *     // If absent, main code auto-derives these from `color`
 *     shadeTopRight?: string,   // lighter/yellower edge
 *     shadeBottomLeft?: string, // darker/bluer edge
 *     glow?: { enabled?: boolean, strength?: number } // reserved for later
 *   },
 * }
 */

export const SHAPES = [
  {
    id: 'semicolon',
    name: 'the semicolon',
    grid: [
      'X.X',
    ],
    color: '#5e3f34',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'dot',
    name: 'the dot',
    grid: [
      'X',
    ],
    color: '#bfbfbf',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'donut',
    name: 'the donut',
    grid: [
      'XXX',
      'X.X',
      'XXX',
    ],
    color: '#ff00e6',
    difficulty: 2,
    rotation: { mode: 'any' },
    frequency: 0.25,
  },
  {
    id: 'fat_log',
    name: 'the fat log',
    grid: [
      'XXXXXX',
      'XXXXXX',
    ],
    color: '#4a1700',
    difficulty: 2,
    rotation: { mode: 'any' },
    frequency: 0.25,
  },
  {
    id: 'void',
    name: 'the void',
    grid: [
      '.X.',
      'X.X',
      '.X.',
    ],
    color: '#280042',
    difficulty: 3,
    rotation: { mode: 'any' },
    frequency: 0.10,
  },
  {
    id: 'choker',
    name: 'the choker',
    grid: [
      'X',
      'X',
      'X',
      'X',
      'X',
      'X',
      'X',
      'X',
      'X',
      'X',
      'X',
    ],
    color: '#5e0e41',
    difficulty: 3,
    rotation: { mode: 'none' },
    frequency: 0.10,
  },
  {
    id: 'emoji',
    name: 'the emoji',
    grid: [
      'X.X',
      '...',
      'XXX',
    ],
    color: '#fff700',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.49,
  },
  {
    id: 'dumpling',
    name: 'the dumpling',
    grid: [
      'XXX',
      'XXX',
    ],
    color: '#d2f59e',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'wave',
    name: 'the wave',
    grid: [
      'X.XXX',
      'XXX.X',
    ],
    color: '#0019d6',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.25,
  },
  {
    id: 'angle',
    name: 'the angle',
    grid: [
      'XX',
      'X.',
    ],
    color: '#00c8f0',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'number',
    name: 'number one!',
    grid: [
      '.X.',
      'XX.',
      '.X.',
      '.X.',
      'XXX',
    ],
    color: '#ff0066',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.15,
  },
  {
    id: 'heart',
    name: 'the heart <3',
    grid: [
      'XX.',
      'XXX',
      'XXX',
    ],
    color: '#ff0000',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'plus',
    name: 'the plus',
    grid: [
      '.X.',
      'XXX',
      '.X.',
    ],
    color: '#004cff',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.35,
  },
  {
    id: 'equality',
    name: 'equality',
    grid: [
      'XXX',
      '...',
      'XXX',
    ],
    color: '#7589f0',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'absolute',
    name: 'the absolute worst',
    grid: [
      'X.X.X',
      '.X.X.',
      'X.X.X',
      '.X.X.',
      'X.X.X',
    ],
    color: '#c70000',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.05,
  },
  {
    id: 'amigos',
    name: 'the three amigos',
    grid: [
      'XXXX',
      '....',
      'XXXX',
      '....',
      'XXXX',
    ],
    color: '#007a08',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'balls',
    name: 'poi balls',
    grid: [
      'X....X',
    ],
    color: '#fffcad',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'dude',
    name: 'the lil dude',
    grid: [
      'XX',
    ],
    color: '#c800ff',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'eyes',
    name: 'eyes',
    grid: [
      'XX..XX',
    ],
    color: '#0032c7',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'earth',
    name: 'earth and moon',
    grid: [
      '.....X',
      '......',
      '......',
      '......',
      'XX....',
      'XX....',
    ],
    color: '#00a0f0',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.17,
  },
  {
    id: 'approximate',
    name: 'an less approximate circle',
    grid: [
      '...XXXX...',
      '..XXXXXX..',
      '.XXXXXXXX.',
      '.XXXXXXXX.',
      '.XXXXXXXX.',
      '.XXXXXXXX.',
      '..XXXXXX..',
      '...XXXX...',
    ],
    color: '#865b74',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.05,
  },
  {
    id: 'therefore',
    name: 'therefore',
    grid: [
      '.X.',
      '...',
      'X.X',
    ],
    color: '#808080',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.50,
  },
  {
    id: 'cube',
    name: 'the cube',
    grid: [
      'XX',
      'XX',
    ],
    color: '#151fb2',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'wanted',
    name: 'not quite what you wanted',
    grid: [
      '.X',
      'X.',
      'X.',
      'X.',
    ],
    color: '#45ad00',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.49,
  },
  {
    id: 'dotdotdot',
    name: 'dot dot dot',
    grid: [
      'X.X.X',
    ],
    color: '#312650',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'exclaim',
    name: '!!!!',
    grid: [
      'X',
      'X',
      'X',
      '.',
      'X',
    ],
    color: '#9e1000',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'zig',
    name: 'the zig',
    grid: [
      '.X.',
      'X.X',
    ],
    color: '#cda4d5',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'zag',
    name: 'the zig zag',
    grid: [
      'X.X.X.',
      '.X.X..',
    ],
    color: '#682c55',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.49,
  },
  {
    id: 'orbiters',
    name: 'orbiters',
    grid: [
      '..X',
      '...',
      'X..',
    ],
    color: '#8db0b9',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.68,
  },
  {
    id: 'checker',
    name: 'checker',
    grid: [
      '.X',
      'X.',
    ],
    color: '#d6d6d6',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'me',
    name: 'me :D',
    grid: [
      'XXX',
      '.X.',
      '.X.',
    ],
    color: '#beb8e0',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'h',
    name: 'the H',
    grid: [
      'X.X',
      'XXX',
      'X.X',
    ],
    color: '#2ecc87',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'diamond',
    name: 'the diamond',
    grid: [
      '..X..',
      '.XXX.',
      'XXXXX',
      '.XXX.',
      '..X..',
    ],
    color: '#94f3ff',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.12,
  },
  {
    id: 'hammer',
    name: 'the hammer',
    grid: [
      '.X.',
      'XXX',
      'XXX',
    ],
    color: '#665000',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'line',
    name: 'the line',
    grid: [
      'XXX',
    ],
    color: '#cfcdc4',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 1.00,
  },
  {
    id: 'bigangle',
    name: 'the big angle',
    grid: [
      'XXXX',
      'X...',
      'X...',
      'X...',
    ],
    color: '#0008ff',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.18,
  },
  {
    id: 'apple',
    name: 'the apple',
    grid: [
      '..X',
      'XX.',
      'XX.',
    ],
    color: '#ff0033',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.65,
  },
  {
    id: 'touch',
    name: 'the touch',
    grid: [
      'XX.X',
      'X.XX',
    ],
    color: '#4836a6',
    difficulty: 1,
    rotation: { mode: 'any' },
    frequency: 0.37,
  },
];
